# Generated by Django 5.0.6 on 2024-07-12 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_age', models.SmallIntegerField()),
                ('teacher_name', models.CharField(max_length=20)),
                ('teacher_id', models.SmallIntegerField()),
                ('teacher_course', models.CharField(max_length=20)),
                ('teacher_contact', models.CharField(max_length=20)),
                ('teacher_description', models.TextField(max_length=20)),
                ('teacher_occupation', models.CharField(max_length=20)),
                ('teacher_salary', models.SmallIntegerField()),
                ('teacher_headshot', models.ImageField(upload_to='')),
                ('teacher_bank_account', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
