# Generated by Django 5.0.6 on 2024-07-13 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='student',
            new_name='student_id',
        ),
    ]
