# Generated by Django 5.0.6 on 2024-07-13 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_rename_student_teacher_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='student_id',
            new_name='student',
        ),
    ]
