# Generated by Django 5.0.6 on 2024-07-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_rename_student_id_teacher_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_headshot',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
