# Generated by Django 5.0.6 on 2024-07-12 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_capacity', models.SmallIntegerField()),
                ('class_performance', models.CharField(max_length=30)),
                ('class_lecture', models.CharField(max_length=30)),
                ('class_id', models.SmallIntegerField()),
                ('class_name', models.CharField(max_length=30)),
                ('class_representative', models.CharField(max_length=30)),
                ('class_description', models.TextField(max_length=30)),
                ('class_table_number', models.SmallIntegerField()),
                ('class_bio', models.CharField(max_length=30)),
                ('class_rules', models.CharField(max_length=30)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
