# Generated by Django 5.0.6 on 2024-07-12 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='student_id',
            new_name='student',
        ),
    ]
