# Generated by Django 5.0.6 on 2024-07-13 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_rename_student_id_class_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='student',
            new_name='student_id',
        ),
    ]
