# Generated by Django 5.0.6 on 2024-07-13 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_rename_student_classes_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='student_id',
            new_name='student',
        ),
    ]
