# Generated by Django 5.0.7 on 2024-08-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_rename_student_id_classes_student'),
        ('course', '0004_remove_course_id_remove_course_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='student',
        ),
        migrations.AddField(
            model_name='classes',
            name='courses',
            field=models.ManyToManyField(to='course.course'),
        ),
    ]
