# Generated by Django 5.0.7 on 2024-08-17 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_remove_classes_student_classes_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='courses',
        ),
    ]
