# Generated by Django 5.0.7 on 2024-08-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_remove_classes_id_alter_classes_class_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='class_id',
        ),
        migrations.AddField(
            model_name='classes',
            name='id',
            field=models.BigAutoField(primary_key=True),
            preserve_default=False,
        ),
    ]
