# Generated by Django 5.0.7 on 2024-08-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_remove_classes_class_id_classes_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
