# Generated by Django 5.0.7 on 2024-08-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_course_id_remove_course_student_and_more'),
        ('period', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='student',
        ),
        migrations.AddField(
            model_name='period',
            name='courses',
            field=models.ManyToManyField(to='course.course'),
        ),
    ]
