# Generated by Django 5.0.6 on 2024-07-12 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_name', models.CharField(max_length=20)),
                ('courses_code', models.IntegerField()),
                ('courses_TA', models.CharField(max_length=20)),
                ('courses_term', models.CharField(max_length=20)),
                ('courses_description', models.TextField()),
                ('courses_department', models.CharField(max_length=20)),
                ('courses_syllabus', models.CharField(max_length=20)),
                ('courses_instructor', models.CharField(max_length=20)),
                ('courses_duration', models.SmallIntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
