# Generated by Django 5.0.6 on 2024-07-16 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_rename_courses_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='courses_TA',
            new_name='course_TA',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='courses_code',
            new_name='course_code',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='courses_department',
            new_name='course_department',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='courses_description',
            new_name='course_description',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='courses_duration',
            new_name='course_duration',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='courses_instructor',
            new_name='course_instructor',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='courses_name',
            new_name='course_name',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='courses_syllabus',
            new_name='course_syllabus',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='courses_term',
            new_name='course_term',
        ),
    ]
