# Generated by Django 5.0.6 on 2024-07-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('code', models.SmallIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('age', models.SmallIntegerField()),
                ('phone_number', models.CharField(max_length=20)),
                ('next_of_kin', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('bio', models.TextField()),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
